### PR TITLE
Fixed #30, problem with incremental sync strategy database_id mismatc…

### LINKED ISSUE #30: Incremental sync strategy fails on Azure SQL when db_id is different to sys.change_tracking_databases entry
I had change tracking enabled on an Azure SQL database and wanted to do an incremental sync using Stitch, it was blowing up with `Change Tracking is not enabled for database`. Long story short, in the code [here](https://github.com/singer-io/tap-mssql/blob/0e7b418253032caa2c647a86404a429c2a41dba3/src/tap_mssql/sync_strategies/logical.clj#L33-L34) I see the trouble stems from `SELECT DB_NAME(database_id) AS db_name FROM sys.change_tracking_databases`.

For some bizarre reason, in Azure SQL, the database ID numbers in `sys.*` tables can fall out of sync with the database ID numbers used by `DB_NAME()` and `DB_ID()` (see [note in Microsoft docs](https://docs.microsoft.com/en-us/sql/t-sql/functions/db-id-transact-sql?view=sql-server-ver15#remarks)), and this query directly compares the two, so my valid entry in `sys.change_tracking_databases` was put through `DB_NAME()` which output `NULL`.

The MS-recommended solution is to compare like for like, i.e. to look up the name from `sys.databases` instead.

PR to follow!

### PR DESCRIPTION
**Pull request by kamd**
Fixed #30, problem with incremental sync strategy database_id mismatch in Azure SQL.

DB_NAME can give inconsistent results with the database_ids from sys.change_tracking_databases on Azure SQL, this fix joins with sys.databases instead.

### CODE REVIEW

**Comment by cmerrick** [comment]
Hi @kamd, thanks for your contribution!

In order for us to evaluate and accept your PR, we ask that you [sign a contribution license agreement](https://stitch-cla-enforcer.herokuapp.com/). It's all electronic and will take just minutes.

**Comment by cmerrick** [comment]
You did it @kamd!

Thank you for signing the Singer Contribution License Agreement.

**Comment by marko220** [comment]
Whats the ETA on getting this merged? Its breaking our integration with StitchData

**Comment by marko220** [comment]
Hi - managed to get this working locally using this branch and can confirm its now working ok for change tracking on an Azure DB with mis-matching database-ids. Currently running it on local VM pushing this data straight at StitchData using an API key. 

To replicate the mis-matching database ids - create a SQL managed DB in Azure, add it to an elastic pool and scale the pool up and down. Its caused when you either scale (which is the easiest to reproduce) or the DB fails over silently behind the scenes on Azures side.

**Comment by marko220** [comment]
@cmerrick any idea when this will be merged?

**Comment by cosimon** [comment]
The changes in this PR have been merged as part of #41

**Pull request closed without merging**
